#PBS -N tune-amptorch-hyperparams
#PBS -l nodes=1:ppn=1:gpus=1
#PBS -l mem=2gb
#PBS -l walltime=02:00:00
#PBS -q pace-ice-gpu

echo "Started on `/bin/hostname`"
echo "Nodes chosen are:"
cat $PBS_NODEFILE

cd ~/bdqm-hyperparam-tuning
source setup-session.sh
ampopt tune \
  --jobs=1 \
  --trials=$trials \
  --study=$study \
  --pruner=$pruner \
  --sampler=$sampler \
  --epochs=$epochs \
  --data=$data \
  --params=env
